### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Raj2032** [audulus/rui#18]
Hey guys I have some questions regarding this project:
1. Can this library be used to integrate into a game engine as easily as somehting like [egui](https://github.com/emilk/egui)
2. Are there any caching capabilities even though it is immediate?
3. Does it compile for web as well?
4. Does it lock you into some kind of framework like [iced](https://iced.rs/) does?

**Comment by wtholliday** [comment]
Hi @Raj2032 :)

1. I don't think so. It doesn't follow the IMGUI pattern of outputting vertex buffers, instead using it's own renderer (https://github.com/audulus/vger-rs)
2. Not yet, though I'm planning to do that.
3. That's a WIP.
4. No. See https://github.com/audulus/rui-ios

**Comment by Raj2032** [comment]
@wtholliday 

1. Is it somehow still possible to support it in game engines?
2. If it does have caching capabilities would it be suitable to be used as retained graphics?
3. Ah right mate :)
4. Interesting mate :) glad it doesn't lock you into some framework or something :)
5. Does rui support Android as well? Or is this WIP?
6. Can I make my GUI application anything I want it to look, for example something like this:

![image](https://user-images.githubusercontent.com/29293830/169494165-354cbd12-5722-4ce8-aa5a-ca65136f90b2.png)

**Comment by wtholliday** [comment]
5. I haven't thought about android. In theory it should work.
6. Yes, though it doesn't have theming, so you'd have to write your own widgets.

BTW, it seems like you may be looking for a more mature toolkit than rui. rui is really very young (only started in February of this year).
