### ISSUE TITLE
wrong display in shapes example on Linux Xorg/Nvidia

### ISSUE THREAD

**Issue by pymongo** [audulus/rui#2]
excepted display a circle and rectangle but the display is confused

![image](https://user-images.githubusercontent.com/42347370/156291820-0a3b6cc4-1cfa-4e50-a1a1-8475d282ebe5.png)

```
[w@ww rui]$ rustc --version
rustc 1.59.0 (9d1b2106e 2022-02-23)
[w@ww rui]$ screenfetch -n
 w@ww
 OS: Manjaro 21.2.4 Qonos
 Kernel: x86_64 Linux 5.10.102-1-MANJARO
 Uptime: 1d 1h 9m
 Packages: 1541
 Shell: bash 5.1.16
 Resolution: 1920x1080
 DE: KDE 5.91.0 / Plasma 5.24.2
 WM: KWin
 GTK Theme: Adwaita-dark [GTK2/3]
 Icon Theme: breeze-dark
 Disk: 247G / 489G (53%)
 CPU: AMD Ryzen 9 5900X 12-Core @ 24x 3.7GHz
 GPU: NVIDIA GeForce GT 1030
 RAM: 20197MiB / 64288MiB
```

all example of rui not working on Linux with Nvidia graphic card

**Comment by wtholliday** [comment]
Seems to be the same issue as on Windows.

**Comment by marcandrebenoit** [comment]
Maybe I try it on ubuntu and my rx570 to see if it's either a manjaro or an Nvidia thing.
#noteToSelf

**Comment by wtholliday** [comment]
Here's the underlying issue: https://github.com/audulus/vger-rs/issues/1

Kinda seems like a bug with wgpu not having consistent memory layout across platforms, but I'm not sure.

**Comment by wtholliday** [comment]
I'm guessing this is the same issue I was seeing on Windows, which is now fixed. Please reopen if you still see it :)
