### ISSUE TITLE
Wrong rendering of Gradient in Windows

### ISSUE THREAD

**Issue by marc2332** [audulus/rui#4]
I tried running the gradient example from the readme in my Windows 10:

```rust
use rui::*;

fn main() {
    rui(canvas(|rect, vger| {
        vger.translate(rect.center() - LocalPoint::zero());

        let paint = vger.linear_gradient(
            [-100.0, -100.0],
            [100.0, 100.0],
            AZURE_HIGHLIGHT,
            RED_HIGHLIGHT,
            0.0,
        );

        let radius = 100.0;
        vger.fill_circle(LocalPoint::zero(), radius, paint);
    }));
}
```

And it looks like:

![image](https://user-images.githubusercontent.com/38158676/156595893-2f3d6d9b-544d-400b-be3a-94f793f51a1b.png)

When it is supposed to look like ( image from the readme ): 

![image](https://user-images.githubusercontent.com/38158676/156596088-62aa1c00-3fe1-411e-ac34-6a57be4561ce.png)

**Comment by wtholliday** [comment]
After updating to the latest wgpu, this now looks good on Windows.

![image](https://user-images.githubusercontent.com/841144/179539487-e51dec28-49b6-4bab-a170-a084d4e9ca13.png)

**Comment by marc2332** [comment]
![image](https://user-images.githubusercontent.com/38158676/179542653-a1b7ff6d-41a6-4417-9411-13c7ec3f22f6.png)
Looks good !
