### ISSUE TITLE
Question: Is there a reason why `Key::Character` takes `&'static str` and not `char`?

### ISSUE THREAD

**Issue by ruza-net** [audulus/rui#43]
I've tried changing this on my local fork, and the tests pass. Is this, however, a deliberate design decision?

**Comment by wtholliday** [comment]
Seems to be because `tao` does it that way: https://docs.rs/tao/0.17.0/tao/keyboard/enum.Key.html

**Comment by ruza-net** [comment]
I use `rui` with the default features, that is, with `winit`. I've tried compiling with `tao`, but there seem to be other issues (e.g. using nonexistent member functions on `tao` structures, among other things). I'll look into why `tao` uses `&str`.

**Comment by wtholliday** [comment]
I'm not opposed to getting rid of `tao` support btw. I wanted to support the Mac menu bar, but given how my app is built, I don't particularly care anymore.

**Comment by ruza-net** [comment]
I'm also not opposed to this.

**Comment by wtholliday** [comment]
Tao is now gone: https://github.com/audulus/rui/pull/45

**Comment by wtholliday** [comment]
@ruza-net want to send me a PR using `char` instead of `'static str`?

**Comment by ruza-net** [comment]
Sure! Sorry, but right now I don't have much time to contribute (I have much to organise with the semester starting)

**Comment by wtholliday** [comment]
@ruza-net No worries! I saw the change already in your repo and thought you deserve credit for it :). I can probably just grab the diff and apply it myself though if you don't have the time.

**Comment by ruza-net** [comment]
Alright, I made a pull request, but I can't make any quality guarantees besides that it compiles and the tests pass :)
