### ISSUE TITLE
Rendering artifacts with vger path fill in canvas

### ISSUE THREAD

**Issue by ruza-net** [audulus/rui#59]
I'm not sure whether this is rui or vger-rs issue, but when I use vger path fill, the filled path "lingers", see attachment.

My code is roughly:
```rust
// start: LocalPoint, end: LocalPoint

canvas(|_cx, _rect, vger| {
    vger.move_to(start);
    vger.quad_to(end, end);
    vger.fill(red_paint);
})
```
![canvas](https://github.com/audulus/rui/assets/6079523/83a952df-62b2-44f0-a1d7-f354e8c4c917)

**Comment by wtholliday** [comment]
Well that's a fun one! Probably a vger issue. I'll work on it soon :)

**Comment by wtholliday** [comment]
I kinda guessed at the problem. Give it a try now and let me know.

Also, would be cool to have a little path drawing example :)

**Comment by ruza-net** [comment]
Great, it works now! (That update also fixed the [issue](https://github.com/audulus/vger-rs/issues/10) with vertical/horizontal strokes)

I might find some time to create that example.
